// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC49-ji7ug19fW9gESLMUupFb6gwH0MciI',
    appId: '1:579367707927:web:b5c2f10435235281c5c352',
    messagingSenderId: '579367707927',
    projectId: 'growtogether-89f1a',
    authDomain: 'growtogether-89f1a.firebaseapp.com',
    storageBucket: 'growtogether-89f1a.firebasestorage.app',
    measurementId: 'G-6Z975LNJKQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtWCfXiYPENVbsLZMHa7Trdf46MhLihVg',
    appId: '1:579367707927:android:299afd331f7e0732c5c352',
    messagingSenderId: '579367707927',
    projectId: 'growtogether-89f1a',
    storageBucket: 'growtogether-89f1a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPef8BL5-fJl2Rvc5p00hj4xmHd97DK7s',
    appId: '1:579367707927:ios:7c4c549074d5a4ebc5c352',
    messagingSenderId: '579367707927',
    projectId: 'growtogether-89f1a',
    storageBucket: 'growtogether-89f1a.firebasestorage.app',
    iosBundleId: 'com.example.growtogether',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPef8BL5-fJl2Rvc5p00hj4xmHd97DK7s',
    appId: '1:579367707927:ios:7c4c549074d5a4ebc5c352',
    messagingSenderId: '579367707927',
    projectId: 'growtogether-89f1a',
    storageBucket: 'growtogether-89f1a.firebasestorage.app',
    iosBundleId: 'com.example.growtogether',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC49-ji7ug19fW9gESLMUupFb6gwH0MciI',
    appId: '1:579367707927:web:1e910c8f745bbb33c5c352',
    messagingSenderId: '579367707927',
    projectId: 'growtogether-89f1a',
    authDomain: 'growtogether-89f1a.firebaseapp.com',
    storageBucket: 'growtogether-89f1a.firebasestorage.app',
    measurementId: 'G-FZ605WG1FP',
  );
}
