// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDB5PjNzpKgZk1kngWx5TceZ-t7UX2nd9w',
    appId: '1:828794375077:web:2938e5d347401f0e60b64c',
    messagingSenderId: '828794375077',
    projectId: 'eomao-dc47e',
    authDomain: 'eomao-dc47e.firebaseapp.com',
    storageBucket: 'eomao-dc47e.firebasestorage.app',
    measurementId: 'G-2Z4GB8S5KE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWpe_q5173mXVKBpPaC6_wyHemA42gkzI',
    appId: '1:828794375077:android:c9e5c4e6c170bea160b64c',
    messagingSenderId: '828794375077',
    projectId: 'eomao-dc47e',
    storageBucket: 'eomao-dc47e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-CfPmJWedmdtWof_e1NnapJE2VB8tm5I',
    appId: '1:828794375077:ios:eb9b424f9b48992e60b64c',
    messagingSenderId: '828794375077',
    projectId: 'eomao-dc47e',
    storageBucket: 'eomao-dc47e.firebasestorage.app',
    iosBundleId: 'com.example.growtogether',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-CfPmJWedmdtWof_e1NnapJE2VB8tm5I',
    appId: '1:828794375077:ios:6784d14993a7582060b64c',
    messagingSenderId: '828794375077',
    projectId: 'eomao-dc47e',
    storageBucket: 'eomao-dc47e.firebasestorage.app',
    iosBundleId: 'com.cnu.growtogether',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDB5PjNzpKgZk1kngWx5TceZ-t7UX2nd9w',
    appId: '1:828794375077:web:f69b36459ac8823660b64c',
    messagingSenderId: '828794375077',
    projectId: 'eomao-dc47e',
    authDomain: 'eomao-dc47e.firebaseapp.com',
    storageBucket: 'eomao-dc47e.firebasestorage.app',
    measurementId: 'G-H7WNV37TPD',
  );

}